export const SCALAR_TYPES = [
    'String',
    'Int',
    'Float',
    'Boolean',
    'ID',
    'Date',
    'DateTime',
    'LocalDate',
    'LocalDateTime',
    'LocalTime',
    'BigInt',
    'BigDecimal',
    'Long',
    'Json',
];